name: Build

on:
  push:
    paths:
      - "src/**"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # SetUp
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install

      # Build
      - run: yarn build

      # Commit
      - uses: EndBug/add-and-commit@v4
        with:
          author_name: Auto Build Chan
          author_email: mail@example.com
          message: "Auto Build"
          add: "docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
