name: CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - uses: actions/upload-artifact
        with:
          name: dist
          path: dist
